### ISSUE TITLE
DietPi instead of Raspbian? 

### ISSUE THREAD

**Issue by msurguy** [ithinkido/PiPlot#1]
I was wondering if you could adjust the scripts to also work on other distributions such as DietPi.

**Comment by ithinkido** [comment]
DietPi does look interesting. The auto install scripts I have made up are for RaspbianOS and work on both the Lite and Full version. The Lite version is very well suited to this project and I would recommend using that.
Alternatively, you could use the manual install steps described in the README to configure your Pi if you would like to run a different OS.

**Comment by msurguy** [comment]
Thanks for your reply, @ithinkido !
